version: '3.4'

networks:
  oconnorevents-network:

services:
  oconnorevents.eventcatalog:
    container_name: oconnoreventseventcatalogapi
    image: ${DOCKER_REGISTRY-}oconnoreventseventcatalog
    build:
      context: .
      dockerfile: OconnorEvents.EventCatalog/Dockerfile
    networks:
      - oconnorevents-network
    depends_on:
      - oconnorevents.sqlserver

  oconnorevents.shoppingbasket:
    container_name: oconnoreventsshoppingbasketapi
    image: ${DOCKER_REGISTRY-}oconnoreventsshoppingbasket
    build:
      context: .
      dockerfile: OconnorEvents.ShoppingBasket/Dockerfile
    networks:
      - oconnorevents-network
    depends_on:
      - oconnorevents.sqlserver

  oconnorevents.sqlserver:
    container_name: oconnoreventsqlserver
    image: "mcr.microsoft.com/mssql/server"
    user: root
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "2@LaiNw)PDvs^t>L!Ybt]6H^%h3U>M"
        ACCEPT_EULA: "Y"
    networks:
      - oconnorevents-network